export const LOGIN_ROUTE = '/login';
export const REGISTRATION_ROUTE = '/registration';
export const ORDERPAGE_ROUTE = '/order';
export const ORDERS_ROUTE = '/orders';
export const PROFILE_ROUTE = '/profile';
export const PROJECTS_ROUTE = '/projects';
export const PROJECT_PAGE_ROUTE = '/project';
export const NEW_PROJECT_ROUTE = '/newproject';
export const NEW_ORDER_ROUTE = '/neworder';
export const NEW_MATERIAL_ROUTE = '/newmaterial';
export const TEAM_ROUTE = '/team';
export const NEW_MEMBER_ROUTE = '/newmember';
export const COSTS_ROUTE = '/costs';
export const NEW_COSTS_ROUTE ='/newcosts'